from databases.connectors.mongodb import MongoDB_Base_R4_Patient
from databases.connectors.mongodb import MongoDB_Base_R4_Encounter

Base_R4_Patient = MongoDB_Base_R4_Patient
Base_R4_Encounter = MongoDB_Base_R4_Encounter
